services:
  proxy:
    build: reverse-proxy
    ports:
      - 9002:80
    depends_on:
      - frontend
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.freehunter-http.rule=Host(`freehunter.iamon99.com`)'
      - 'traefik.http.routers.freehunter-http.entrypoints=web'
      - 'traefik.http.routers.freehunter-http.middlewares=freehunter-https'
      - 'traefik.http.middlewares.freehunter-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.freehunter.rule=Host(`freehunter.iamon99.com`)'
      - 'traefik.http.routers.freehunter.entrypoints=websecure'
      - 'traefik.http.routers.freehunter.tls.certresolver=myresolver'
      - 'traefik.http.services.freehunter.loadbalancer.server.port=80'

  frontend:
    build: frontend
    # ports:
    # - 80
    # volumes:
    # - frontend:/src
    command: yarn start

volumes:
  data:
